name: 'Test modifying a Rubik Pi tar image'
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Test using downloaded (cached) image
        id: test_download_image
        uses: ./  # photonvision/photon-image-runner@HEAD
        with:
          image_url: https://github.com/PhotonVision/photon-image-modifier/releases/download/v2027.0.0/photonvision_rubikpi3.tar.xz
          minimum_free_mb: 2000
          root_location: "offset=569376768"
          shrink_image: "no"
          use_cache: "yes"
          commands: |
              echo "Testing Rubik Pi tar image"
              uname -a
              lsblk
              echo "${loopdev}"
              touch /photon-image-modifier-was-here
              ls /

      - name: Test using image file
        id: test_file_image
        uses: ./  # photonvision/photon-image-runner@HEAD
        with:
          image_url: "file://${{ steps.test_download_image.outputs.image }}"
          root_location: "offset=569376768"
          shrink_image: "no"
          use_cache: "yes"
          commands: |
              echo "Testing file access Rubik Pi tar image"
              uname -a
              lsblk
              echo "${loopdev}"
              touch /photon-image-modifier-file-was-here
              ls /

      - name: Compress image
        run: |
            imagedir=$(dirname ${{ steps.test_download_image.outputs.image }})
            echo "Imagedir: ${imagedir}"
            ls -la ${imagedir}
            tardir=photonvision_rubikpi3_fromTAR
            mkdir --parents ${tardir}
            echo "Tardir: ${tardir}"
            ls -la ${tardir}
            sudo mv ${imagedir}/* ${tardir}/
            echo "After move"
            ls -la ${tardir}
            sudo tar -I 'zstdmt -10' -cf ./photonvision_rubikpi3_fromTAR.tar.zst ${tardir} --checkpoint=10000 --checkpoint-action=echo='%T'

      - uses: actions/upload-artifact@v6
        with:
          name: photonvision_rubikpi3_fromTAR.tar.zst
          path: ./photonvision_rubikpi3_fromTAR.tar.zst
          compression-level: 0
          if-no-files-found: error
          retention-days: 1


